name: [WIP] Auto deploy prebuilt site
on: workflow_dispatch
## OLD
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - 'main'
#     paths:
#       - 'resources/public/**'

## NEW
## See that npm only jumps to action when the source is rebuilt, not static files (html, css)
# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - 'main'
#     paths:
#       - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Cache node
        uses: actions/cache@v3.0.1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm install
          npm run release

      - name: S3 Deploy
        uses: Reggionick/s3-deploy@v3.1.1
        with:
          folder: resources/public
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          dist-id: ${{ secrets.CLOUDFRONT_DIST_ID }}
          invalidation: /*
          delete-removed: true
          # Use this parameter to specify Cache-Control: no-cache, no-store, must-revalidate header
          # no-cache: # optional
          private: true
