name: Ping files

on: workflow_dispatch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Test activities
        run: |
          pwd
          echo ~
          echo "====================================================="
          echo "tree -daL 2 /home"
          tree -daL 2 /home
          echo "====================================================="
          echo "tree -daL 2 ."
          tree -daL 2 .
          echo "====================================================="
          echo "tree -daL 3 /home/runner/work"
          tree -daL 3 /home/runner/work
